./simtask.py  e 0 > output/out.0 2> output/err.0
./simtask.py   1 2 3 1 > output/out.1 2> output/err.1
./simtask.py   1 2 3 2 > output/out.2 2> output/err.2
./simtask.py   1 2 3 3 > output/out.3 2> output/err.3
./simtask.py   1 2 3 4 > output/out.4 2> output/err.4
./simtask.py   1 2 3 5 > output/out.5 2> output/err.5
./simtask.py   1 2 3 6 > output/out.6 2> output/err.6
./simtask.py   1 2 3 7 > output/out.7 2> output/err.7
./simtask.py   1 2 3 8 > output/out.8 2> output/err.8
./simtask.py   1 2 3 9 > output/out.9 2> output/err.9
./simtask.py   1 2 3 9 > output/out.10 2> output/err.11
[[b'', b'', 1], [b'', b'', 1], [b'', b'', 1], [b'', b'', 1], [b'', b'', 244], [b'', b'', 0], [b'', b'', 1], [b'', b'', 1], [b'', b'', 244], [b'', b'', 1], [b'', b'', 1]]
